BAH-1670, BAH-1796 - Dockerized and refactored Hip-atomfeed-listener
Bahmni-Covid19/hip-atomfeed-listener pull request #2
Opened 2022-06-22 07:57 UTC by SanoferSameera

2022-07-01 08:35 UTC, swatigogia2020 requested changes

2022-07-01 08:35 UTC, swatigogia2020 commented on docker-compose.yml
> +      - DATABASE_NAME=bahmni_pacs
need to refactor name

2022-07-01 08:35 UTC, swatigogia2020 commented on hip-atomfeed/src/main/java/org/bahmni/module/hipfeedintegration/atomfeed/client/Constants.java
> +    public static final String PACS_CONCEPT_SOURCE_NAME = "PACS Procedure Code";
are we using this string?

2022-07-01 08:35 UTC, swatigogia2020 commented on hip-atomfeed/src/main/java/org/bahmni/module/hipfeedintegration/services/HipService.java
> +    String newCareContext = "/hiprovider/v0.5/hip/new-carecontext";
we can move this to constant file

2022-07-01 08:35 UTC, swatigogia2020 commented on hip-atomfeed/src/main/java/org/bahmni/module/hipfeedintegration/services/HipService.java
> +        logger.warn("===========================request begin================================================");
Once tested remove the warning log, maybe have a short meaningful debug log

2022-07-01 08:35 UTC, swatigogia2020 commented on hip-atomfeed/src/main/java/org/bahmni/module/hipfeedintegration/services/OpenMRSService.java
> +    String globalPropertyurl = "/openmrs/ws/rest/v1/systemsetting/";
can we move these APIs to constant file

2022-07-06 05:37 UTC, N0-man approved these changes

2022-07-06 07:03 UTC, merged